# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BaseDemo' do
#AutoLayout
pod 'Masonry'
end

target 'BaseDemoTests' do

end

target 'BaseDemoUITests' do

end

